#!/bin/bash

# Copyright 2014 Michal Wirth <wirthmi@rankl.cz>
#
# The Heslovatko script is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# The Heslovatko script is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with the Heslovatko script. If not,see <http://www.gnu.org/licenses/>.

recipient="some-public-key-id-eg-email"

set -e

if [ $# -ne 1 ]; then
  echo "heslovatko: expecting exactly ONE file parameter" 1>&2
  exit 1
fi

file=$1

encrypting_command="gpg --encrypt --armor \
  --recipient \"${recipient}\" --output \"${file}\" --batch --yes"

gpg --decrypt --use-agent "${file}" |vim - -n -i "NONE" \
  "+command Write w !${encrypting_command}" \
  "+command Quit q!" \
  "+cabbrev w :Write" \
  "+cabbrev q :Quit" \
  "+cabbrev wq :Write<CR>:Quit"
